---
- name: ping hosts
  ping:

- name: check OS
  debug: msg={{ansible_os_family}}-{{ansible_distribution}}{{ansible_distribution_version}}-{{ansible_distribution_release}}

- name: install gnupg2 for debian, ubuntu
  apt:
    name: gnupg2
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: add an nginx apt signing key
  ansible.builtin.apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  when: ansible_os_family == "Debian"

# debian
- name: add nginx repo for debian
  ansible.builtin.apt_repository:
    repo: deb http://nginx.org/packages/debian {{ansible_distribution_release}} nginx
    validate_certs: yes
    state: present
    filename: nginx
  when: ansible_distribution == "Debian"

# ubuntu
- name: add nginx repo for ubuntu
  ansible.builtin.apt_repository:
    repo: deb http://nginx.org/packages/ubuntu {{ansible_distribution_release}} nginx
    validate_certs: yes
    state: present
    filename: nginx
  when: ansible_distribution == "Ubuntu"

- name: install nginx for debian, ubuntu
  apt:
    name: nginx
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

# centos/redhat
- name: add repository for centos
  yum_repository:
    name: nginx
    description: nginx stable repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: install nginx for RedHat
  yum:
    name: nginx
    state: latest
  when: ansible_os_family == "RedHat"

- name: enable nginx and ensure it is not masked
  systemd:
    name: nginx
    enabled: yes
    masked: no

- name: make sure nginx is started
  systemd:
    state: started
    name: nginx
