---
- hosts: "{{ hosts }}"
  vars:
    php_version: 8.2 # You can change PHP version to your needs
  roles: # Uncomment required software
    - docker
    - nginx
    - mariadb
    - php
    - certbot