---
- name: Ping hosts
  ping:

- name: Check OS
  ansible.builtin.debug: msg={{ ansible_os_family }}-{{ ansible_distribution }}{{ ansible_distribution_version }}-{{ ansible_distribution_release }}

- name: Install gnupg2
  ansible.builtin.apt:
    name: gnupg2
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add mariadb apt signing key
  ansible.builtin.apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present
  when: ansible_os_family == "Debian"

- name: Add mariadb repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] https://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.10/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main
    validate_certs: yes
    state: present
    filename: mariadb
  when: ansible_os_family == "Debian"

- name: Install mariadb-server
  apt:
    name: mariadb-server
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: Enable MariaDB-server and ensure it is not masked
  systemd:
    name: mariadb
    enabled: yes
    masked: no

- name: Make sure MariaDB-server is started
  systemd:
    state: started
    name: mariadb
