---
- name: ping hosts
  ping:

- name: check OS
  debug: msg={{ ansible_os_family }}-{{ ansible_distribution }}{{ ansible_distribution_version }}-{{ ansible_distribution_release }}

- name: install gnupg2 for debian, ubuntu
  apt:
    name: gnupg2
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: add mariadb apt signing key
  ansible.builtin.apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present
  when: ansible_os_family == "Debian"

# debian
- name: add mariadb repo for debian
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] https://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.5/debian {{ ansible_distribution_release }} main
    validate_certs: yes
    state: present
    filename: mariadb
  when: ansible_distribution == "Debian"

# ubuntu
- name: add mariadb repo for ubuntu
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] https://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.5/ubuntu {{ ansible_distribution_release }} main
    validate_certs: yes
    state: present
    filename: mariadb
  when: ansible_distribution == "Ubuntu"

- name: install mariadb-server for debian, ubuntu
  apt:
    name: mariadb-server
    update_cache: yes
  when: ansible_os_family == "Debian"

# centos
- name: add repository for centos
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.5/centos{{ ansible_distribution_major_version }}-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == "RedHat"

# CentOS
- name: module_hotfixes=1 for ansible < 2.11
  lineinfile:
    path: /etc/yum.repos.d/mariadb.repo
    line: module_hotfixes=1
  when: ansible_os_family == "RedHat"

- name: install MariaDB-server for CentOS
  yum:
    name: MariaDB-server
  when: ansible_os_family == "RedHat"

- name: enable MariaDB-server and ensure it is not masked
  systemd:
    name: mariadb
    enabled: yes
    masked: no

- name: make sure MariaDB-server is started
  systemd:
    state: started
    name: mariadb
