---
- name: ping hosts
  ping:

- name: check OS
  debug: msg={{ ansible_os_family }}-{{ ansible_distribution }}{{ ansible_distribution_version }}-{{ ansible_distribution_release }}

# ==== Debian/Ubuntu ====
- name: preinstallations for Debian/Ubuntu
  apt:
    name:
      - gnupg2
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl
      - sudo
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: add sury.org GPG key for Debian
  shell: curl -sSL https://packages.sury.org/php/apt.gpg | sudo apt-key add -
  when: ansible_distribution == "Debian"

- name: add sury.org repo for Debian
  ansible.builtin.apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    validate_certs: yes
    state: present
    filename: php
  when: ansible_distribution == "Debian"

- name: add sury.org repo for Ubuntu
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
  when: ansible_distribution == "Ubuntu"

- name: install PHP8.0 for debian, ubuntu
  apt:
    name:
      - php8.0
      - php8.0-fpm
      - php8.0-gd
      - php8.0-xml
      - php8.0-soap
      - php8.0-mbstring
      - php8.0-mysql
      - php8.0-imap
      - php8.0-curl
      - php8.0-zip
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: enable PHP8.0-FPM and ensure it is not masked for Debian/Ubuntu
  systemd:
    name: php8.0-fpm
    enabled: yes
    masked: no
  when: ansible_os_family == "Debian"

- name: make sure PHP8.0-FPM is started for Debian/Ubuntu
  systemd:
    state: started
    name: php8.0-fpm
  when: ansible_os_family == "Debian"

# ==== CentOS ====
- name: add EPEL repo for CentOS
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  when: ansible_os_family == "RedHat"

- name: add REMI repo for CentOS
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
  when: ansible_os_family == "RedHat"

- name: install yum-utils for CentOS
  yum:
    name: yum-utils
  when: ansible_os_family == "RedHat"

- name: disable other PHP versions for CentOS7
  shell: yum-config-manager --disable 'remi-php*'
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

- name: enable PHP8.0 repo for CentOS7
  shell: yum-config-manager --enable remi-php80
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

- name: disable other PHP versions for CentOS8
  shell: dnf module reset php -y
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"

- name: enable PHP8.0 repo for CentOS8
  shell: dnf module install php:remi-8.0 -y
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"

- name: install PHP8.0 from REMI repo
  yum:
    name:
      - php
      - php-fpm
      - php-gd
      - php-xml
      - php-soap
      - php-mbstring
      - php-mysql
      - php-imap
      - php-curl
      - php-zip
  when: ansible_os_family == "RedHat"

- name: enable PHP-FPM and ensure it is not masked for CentOS
  systemd:
    name: php-fpm
    enabled: yes
    masked: no
  when: ansible_os_family == "RedHat"

- name: make sure PHP-FPM is started for CentOS
  systemd:
    state: started
    name: php-fpm
  when: ansible_os_family == "RedHat"
